permalink: /:year/:month/:day/:title.html # 博文的固定链接
paginate: 10 #每页的博文数量
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: Tin Kai
  email: gttiankai@163.com
  link: gttiankai.github.io
  github: http://github.com/gttiankai

# 站点信息
title: Tiankai`s Blog
description: Tiankai`s Blog
url: gttiankai.github.io
rss_url: /pages/atom.xml
iamge_url: http://gttiankai.github.com/public/img
# gavatar头像及Favicon
gavatar: /public/img/mypicture.png
#favicon: 

# google analytics 设置
ga:
  id: UA-54767140-1
  url: gttiankai.github.io

# disqus 设置
disqus:
  shortname: Tiankai-zh

# 主题设置，自动激活某个标签
active: tags

# 首页除了最新文章外显示分类
cates: 
  - Android 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
