#+TITLE: github jekyll org-mod 写blog for Mac
* 前言
今天晚上在看文章的时候突然想起来上次没有成功使用github+org-mode+jekyll写blog的事情,今晚正好有时间,所以就索性配置一下,将自己配置遇到的问题,记录下来,以方便大家如果遇到我出现的问题,可以快速的结果.
* 系统情况
Mac OX 10.95
org-mode: emacs24.4.1 自带的org-mode
(至于为什么会写明自己使用的环境,是为了让大家更好的解决问题,因为我自己以前遇到问题,在网上查到了解决方式,可是最后发现和别人使用的环境不同,造成浪费了好多时间,还没有解决问题)
* 关于为什么要这么配置
一开始我是在网上无意中看了文章
* 在github上建立自己的blog
github的官网上有如何使用git page的wiki建立个人blog的指导教程,很详细,大家可以按照上面的步骤一步一步的进行操作,就可以了,并且上面也有使用jekyll,绑定用户自己的域名的介绍,很详细.大家可以看看.所以这里就不在罗嗦了.

链接在这里:[[https://pages.github.com/][github的page页面]] 
(ps:感觉github这个网站做的特别好,很人性化,说的也很详细)
* 搭建Jekyll环境
我看的是github官网上得教程,关于使用Jekyll,但是我在安装工程中遇到一些问题,所以在这里记录下来.

github上关于使用Jekyll的链接在这里:[[https://help.github.com/articles/using-jekyll-with-pages/][Using Jekyll with Pages]]

** 安装 Ruby
上面的教程中虽然说了在Mac系统已经安装了Ruby,所以不需要安装Ruby了,但是我已开始尝试的时候,发现在进行第二步安装bundler的过程中,不能正常安装提示权限问题,问了一下google,发现一篇blog([[http://blog.lessfun.com/blog/2014/05/20/clone-exists-octopress-blog-to-new-mac/][链接]]),上面说如果直接使用sudo命令继续安装,在后边会继续遇到问题(ps:本人没有亲自尝试).所以本人重新安装了Ruby,安装命令如下:
#+BEGIN_SRC shell
brew install ruby
#+END_SRC
安装完成之后,我使用ruby -version 命令显示的还是原来系统安装的ruby-2.0.0,不是新安装的ruby-2.2.0(应该是shell得配置文件还没有起作用),这个时候不能直接进行下一步的安装,可以重启当前的shell.

然后就可以下面的安装了.
** 安装 bundler
安装
gem install bundler

如果遇到下面的问题,请重新进行上一步安装Ruby的操作
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
** 安装Jekyll
在github下的要作为blog的仓库的目录下创建一个名为Gemfile的文件.文件的内容如下:
#+begin_example 
  source 'https://rubygems.org'
  gem 'github-pages'
#+end_example
然后执行命令 bundle install,进行安装Jekyll.
ps: 在安装的过程中有可能会出现问题,别担心,上面会有提示该怎么操作,只要按上面的提示,进行操作,然后重新执行命令: bundle insatll 就可以了.
* Running Jekyll 
根据github上得教程运行安装好的Jekyll,
#+BEGIN_SRC shell
bundle exec jekyll serve or (jekyll server)
#+END_SRC
当你执行这条指令的时候,终端中会提示你开启的jekyll服务器是否成功,如果成功,然后在浏览器中打开http://localhost:4000/, 会出现下面的错误
#+begin_example 
Forbidden
no access permission to `/'
#+end_example
看到这个先不要着急,在安装jekyll的过程中,会生成一个_site文件夹,如果里面有html文件的话,你试着访问这个文件,我在_site文件夹下面有个hello.html的页面,使用虾下面的URL试一下:
#+begin_example 
  http://localhost:4000/hello.html
#+end_example
如果正常实现,说明我们已经将Jekyll正确的安装了.


* Configuring Jekyll
按照github帮助网页上得说明进行配置就可以.